from PySide2 import QtWidgets

from maya.app.general.mayaMixin import MayaQWidgetDockableMixin


class RigBuildView(MayaQWidgetDockableMixin, QtWidgets.QWidget):
    WINDOW_TITLE = "Auto Rigging"
    OBJECT_NAME = "MayaCppPluginRigBuildPanel"

    def __init__(self, module_names, parent=None):
        super(RigBuildView, self).__init__(parent=parent)

        self.setObjectName(self.OBJECT_NAME)
        self.setWindowTitle(self.WINDOW_TITLE)
        self.setMinimumWidth(360)
        self.resize(450, 500)

        self.create_widgets(module_names)
        self.create_layout()

    # ------------------------------------------------------------------
    # Widgets
    # ------------------------------------------------------------------

    def create_widgets(self, module_names):
        self.tabs = QtWidgets.QTabWidget()

        self.full_body_tab = QtWidgets.QWidget()
        self.module_tab = QtWidgets.QWidget()

        # Full-body tab
        self.create_full_body_guides_button = QtWidgets.QPushButton(
            "Create Full Body Guides"
        )

        self.build_full_body_button = QtWidgets.QPushButton(
            "Build bones and controllers"
        )

        self.configure_large_button(self.create_full_body_guides_button)
        self.configure_large_button(self.build_full_body_button)

        self.full_body_description = QtWidgets.QLabel(
            "Creates Spine, Head, Left Arm and Left Leg guides.\n"
            "Arm and Leg right-side bones are generated by Mirror."
        )
        self.full_body_description.setWordWrap(True)
        self.full_body_description.setAlignment(
            self.full_body_description.alignment()
        )

        # Module tab
        self.module_label = QtWidgets.QLabel("Module")

        self.module_combo_box = QtWidgets.QComboBox()
        self.module_combo_box.addItems(module_names)

        self.side_label = QtWidgets.QLabel("Side")
        self.side_combo_box = QtWidgets.QComboBox()

        self.fk_check_box = QtWidgets.QCheckBox("FK")
        self.fk_check_box.setChecked(True)

        self.ik_check_box = QtWidgets.QCheckBox("IK")
        self.ik_check_box.setChecked(True)

        self.mirror_check_box = QtWidgets.QCheckBox("Mirror")
        self.mirror_check_box.setChecked(False)

        self.create_module_guides_button = QtWidgets.QPushButton(
            "Create Module Guides"
        )

        self.build_module_button = QtWidgets.QPushButton(
            "Build Module Bones and Controllers"
        )

        self.create_module_guides_button.setMinimumHeight(36)
        self.build_module_button.setMinimumHeight(42)

    @staticmethod
    def configure_large_button(button):
        button.setMinimumWidth(280)
        button.setMinimumHeight(64)

        font = button.font()
        font.setPointSize(12) # font size
        font.setBold(True)
        button.setFont(font)

    # ------------------------------------------------------------------
    # Layout
    # ------------------------------------------------------------------

    def create_layout(self):
        self.create_full_body_layout()
        self.create_module_layout()

        self.tabs.addTab(
            self.full_body_tab,
            "Full Body"
        )
        self.tabs.addTab(
            self.module_tab,
            "Module"
        )

        main_layout = QtWidgets.QVBoxLayout(self)
        main_layout.setContentsMargins(12, 12, 12, 12)
        main_layout.addWidget(self.tabs)

    def create_full_body_layout(self):
        create_guides_layout = QtWidgets.QHBoxLayout()
        create_guides_layout.addStretch()
        create_guides_layout.addWidget(
            self.create_full_body_guides_button
        )
        create_guides_layout.addStretch()

        build_layout = QtWidgets.QHBoxLayout()
        build_layout.addStretch()
        build_layout.addWidget(
            self.build_full_body_button
        )
        build_layout.addStretch()

        layout = QtWidgets.QVBoxLayout(self.full_body_tab)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(16)

        layout.addLayout(create_guides_layout)
        layout.addWidget(self.full_body_description)
        layout.addWidget(self.create_separator())
        layout.addLayout(build_layout)
        layout.addStretch()

    def create_module_layout(self):
        selection_layout = QtWidgets.QFormLayout()
        selection_layout.setHorizontalSpacing(12)
        selection_layout.setVerticalSpacing(8)

        selection_layout.addRow(self.module_label, self.module_combo_box)
        selection_layout.addRow(self.side_label, self.side_combo_box)

        rig_type_layout = QtWidgets.QHBoxLayout()
        rig_type_layout.addWidget(self.fk_check_box)
        rig_type_layout.addWidget(self.ik_check_box)
        rig_type_layout.addStretch()

        options_layout = QtWidgets.QFormLayout()
        options_layout.setHorizontalSpacing(12)
        options_layout.setVerticalSpacing(8)

        options_layout.addRow(
            QtWidgets.QLabel("Rig Type"),
            rig_type_layout
        )
        options_layout.addRow(
            QtWidgets.QLabel("Build Options"),
            self.mirror_check_box
        )

        buttons_layout = QtWidgets.QVBoxLayout()
        buttons_layout.setSpacing(12)
        buttons_layout.addWidget(self.create_module_guides_button)
        buttons_layout.addWidget(self.build_module_button)

        layout = QtWidgets.QVBoxLayout(self.module_tab)
        layout.setContentsMargins(12, 12, 12, 12)
        layout.setSpacing(12)

        layout.addLayout(selection_layout)
        layout.addWidget(self.create_separator())
        layout.addLayout(options_layout)
        layout.addWidget(self.create_separator())
        layout.addLayout(buttons_layout)
        layout.addStretch()

    @staticmethod
    def create_separator():
        separator = QtWidgets.QFrame()
        separator.setFrameShape(QtWidgets.QFrame.HLine)
        separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        return separator